CREATE TABLE CUSTOMER (
	CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255),
    MOBILE_NUMBER VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(255),
	VERSION INT NOT NULL,
	CREATED_BY VARCHAR(255) NOT NULL,
	CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UNIQUE(MOBILE_NUMBER, EMAIL)
);