CREATE TABLE ORDERS(
	ORDER_ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	PRODUCT VARCHAR(255) NOT NULL,
	ORDER_STATUS VARCHAR(255),
    ORDER_TIME TIMESTAMP,
    SHIP_TIME TIMESTAMP,
	CANCEL_TIME TIMESTAMP,
	CANCEL_REASON VARCHAR(255),
	VERSION INT NOT NULL,
	CREATED_BY VARCHAR(255) NOT NULL,
	CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);