CREATE TABLE EMAIL(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	RECIPIENT VARCHAR(255) NOT NULL,
	SUBJECT VARCHAR(255) NOT NULL,
	BODY VARCHAR(2000),
	VERSION INT NOT NULL,
	CREATED_BY VARCHAR(255) NOT NULL,
	CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);