INSERT INTO CUSTOMER  VALUES(1, 'Tom', 'Cruise', '87654321', 'ex@email.com', 1, 'SYSTEM',  CURRENT_TIMESTAMP);
INSERT INTO CUSTOMER  VALUES(2, 'Jane', 'Kim', '98765432', 'abc@email.com', 1, 'SYSTEM',  CURRENT_TIMESTAMP);

INSERT INTO ORDERS  VALUES(1, 1, 'Mac', 'Received', CURRENT_TIMESTAMP, null, null, null, 1, 'SYSTEM',  CURRENT_TIMESTAMP);
INSERT INTO ORDERS  VALUES(2, 1, 'Ipad', 'Shipped', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, null, null, 1, 'SYSTEM',  CURRENT_TIMESTAMP);
INSERT INTO ORDERS  VALUES(3, 2, 'Dell', 'Cancelled', CURRENT_TIMESTAMP, null, CURRENT_TIMESTAMP, 'Incorrect order', 1, 'SYSTEM',  CURRENT_TIMESTAMP);
INSERT INTO ORDERS  VALUES(4, 2, 'HP', 'Received', CURRENT_TIMESTAMP, null, null, null, 1, 'SYSTEM',  CURRENT_TIMESTAMP);