CREATE TABLE T_LOG (
	LOG_ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	IP_ADDRESS VARCHAR(255),
	METHOD VARCHAR(255),
	NAME VARCHAR(255),
    INPUT_PARAMS VARCHAR(2000),
    REQUESTED_TIME TIMESTAMP,
	VERSION INT NOT NULL,
	CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	LAST_UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);